name: .NET CI

permissions:
  contents: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x.x'

    - name: Publish Linux build
      run: dotnet publish -c Release -r linux-x64 --self-contained true -o ./publish/khid_csharp-linux

    - name: Publish Windows build
      run: dotnet publish -c Release -r win-x64 --self-contained true -o ./publish/khid_csharp-windows

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}

    - name: Upload Linux build
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./publish/linux
        asset_name: khid_csharp-linux.zip
        asset_content_type: application/zip

    - name: Upload Windows build
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./publish/windows
        asset_name: khid_csharp-windows.zip
        asset_content_type: application/zip